### ISSUE TITLE
"Could not find Windows Runtime type Windows.ApplicationModel.Calls.PhoneLine" in AMD64 Windows 10 "1803" 17134

### ISSUE THREAD

**Issue by ADeltaX** [ADeltaX/MobileShell#2]

**Comment by Aarklendoia** [comment]
I want to compile it on Windows 10 1903 (x64). The Windows dependency is missing and I don't find how to add it.

Maybe a component is missing in my Visual Studio installation? I use Visual Studio 2019 16.1.1.

![MobileShell - Microsoft Visual Studio 04_06_2019 10_02_48](https://user-images.githubusercontent.com/1765298/58861977-ede33500-86af-11e9-87d1-9a560a1e1a0b.png)

**Comment by Aarklendoia** [comment]
Ok, I found it (thanks to Abdel D.). The file is in C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17134.0\Windows.winmd (but why I don't found it myself?).

**Comment by ShadowEO** [comment]
Not sure, in my case, VS 2019 picked up the SDK and automatically referenced it properly (this was from a clean install of VS Community).

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
